api/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'api'
urlpatterns  = [
	url(r'^results/$', views.results, name='results'),
	url(r'^facilities/$', views.facilities, name='facilities'),
	url(r'^samples/$', views.samples, name='samples'),
	url(r'^update_dispatch_details/$', views.update_dispatch_details, name='update_dispatch_details'),
]

results/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from easy_pdf.views import PDFTemplateView
from .views import HelloPDFView
from . import views

app_name = 'results'
urlpatterns  = [
	url(r'^upload/(?P<worksheet_id>[0-9]+)/$', login_required(views.upload), name='upload'),
	url(r'^release_list/(?P<machine_type>[A|R|C])/$', login_required(views.release_list), name='release_list'),
	url(r'^release_results/(?P<worksheet_id>[0-9]+)/$', login_required(views.release_results), name='release_results'),
	url(r'^cobas_upload/$', login_required(views.cobas_upload), name='cobas_upload'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^worksheet/(?P<worksheet_id>[0-9]+)/$', login_required(views.worksheet_results), name='worksheet'),
	url(r'^api', login_required(views.api), name='api'),
	url(r'^anomalies/(?P<worksheet_id>[0-9]+)/$', login_required(views.get_anomalies), name='anomalies'),
	url(r'^intervene_list/$', login_required(views.intervene_list), name='intervene_list'),
	url(r'^reschedule/(?P<result_pk>[0-9]+)/$', login_required(views.reschedule), name='reschedule'),
	url(r'^authorize_sample/$', login_required(views.authorize_sample), name='authorize_sample'),
	url(r'^release_sample/$', login_required(views.release_sample), name='release_sample'),
	url(r'^print_results/(?P<result_id>[0-9]+)/(?P<worksheet_id>[0-9]+)/$', login_required(views.print_results), name='print_results'),
	#url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^hello.pdf$', HelloPDFView.as_view()),
]

samples/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views, data_table_views

app_name = 'samples'

urlpatterns  = [
	#url(r'^$', views.index, name='list_samples'),
	url(r'^create/$', login_required(views.create), name='create'),
	url(r'^get_facility/(?P<form_number>[\w-]+)/$', login_required(views.get_facility), name='get_facility'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^list_json$', login_required(data_table_views.ListJson.as_view()), name='list_json'),
	url(r'^show/(?P<sample_id>[0-9]+)$', login_required(views.show), name='show'),
	url(r'^edit/(?P<sample_id>[0-9]+)$', login_required(views.edit), name='edit'),
	url(r'^verify_list/$', login_required(views.verify_list), name='verify_list'),
	url(r'^verify/(?P<sample_id>[0-9]+)/$', login_required(views.verify), name='verify'),
	url(r'^verify_envelope/(?P<envelope_id>[0-9]+)/$', login_required(views.verify_envelope), name='verify_envelope'),
	url(r'^save_verify/$', login_required(views.save_verify), name='save_verify'),
	url(r'^verify_list_json$', login_required(data_table_views.VerifyListJson.as_view()), name='verify_list_json'),
	url(r'^get_district_hub/(?P<facility_id>[0-9]+)/$', login_required(views.get_district_hub), name='get_district_hub'),
	url(r'^patient_history/(?P<facility_id>[0-9]+)/$', login_required(views.pat_hist), name='pat_hist'),
	url(r'^clinicians/(?P<facility_id>[0-9]+)/$', login_required(views.clinicians), name='clinicians'),
	url(r'^lab_techs/(?P<facility_id>[0-9]+)/$', login_required(views.lab_techs), name='lab_techs'),
	url(r'^release_rejects/$', login_required(views.release_rejects), name='release_rejects'),
	url(r'^released_rejects/$', login_required(views.released_rejects), name='released_rejects'),
	url(r'^intervene_list/$', login_required(views.intervene_list), name='intervene_list'),

	url(r'^vl_list/$', login_required(data_table_views.vl_list), name="vl_list"),
	url(r'^vl_list/data/$', login_required(data_table_views.vl_list_data), name="vl_list_data"),

	url(r'^search/$', login_required(views.search), name='search'),

	url(r'^envelope_list/$', login_required(views.envelope_list), name="envelope_list"),
	url(r'^envelope_list_json/$', login_required(data_table_views.envelope_list_json), name='envelope_list_json'),
	url(r'^generate_forms/$', login_required(views.generate_forms), name="generate_forms"),
	url(r'^forms/$', login_required(views.forms), name="forms"),
	url(r'^edit_dispatch/(?P<dispatch_id>[0-9]+)/$', login_required(views.edit_dispatch), name="edit_dispatch"),
	url(r'^reverse_approval/(?P<verification_id>[0-9]+)/$', login_required(views.reverse_approval), name="reverse_approval"),
	url(r'^download/(?P<path>.*)$',login_required(views.download), name="download"),
	url(r'^reports/$',login_required(views.reports), name="reports"),
	url(r'^print_rejects/(?P<sample_id>[0-9]+)/$', login_required(views.print_rejects), name='print_rejects'),
]

viral_load2/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from home import views as home_views, session

urlpatterns = [
	url(r'^$', home_views.home, name='home_page'),
	url(r'^login/', home_views.login_page, name='login_page'),
	url(r'^login_attempt/', home_views.login_attempt, name='login_attempt'),
	url(r'^logout/', home_views.logout, name='logout'),
	url(r'^quick_stats/', home_views.quick_stats, name='quick_stats'),
	url(r'^change-password/$', auth_views.password_change, {'post_change_redirect': 'home_page'}, name='password_change'),
	url(r'^admin/', admin.site.urls),
	url(r'^samples/', include('samples.urls')),
	url(r'^worksheets/', include('worksheets.urls')),
	url(r'^results/', include('results.urls')),
	url(r'^api/', include('api.urls')),
]

worksheets/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'worksheets'
urlpatterns  = [
	url(r'^create/(?P<machine_type>[A|R|C])$', login_required(views.create), name='create'),
	url(r'^attach_samples/(?P<worksheet_id>[0-9]+)/$', login_required(views.attach_samples), name='attach_samples'),
	url(r'^show/(?P<worksheet_id>[0-9]+)/$', login_required(views.show), name='show'),
	url(r'^edit/(?P<worksheet_id>[0-9]+)/$', login_required(views.edit), name='edit'),
	url(r'^vlprint/(?P<worksheet_id>[0-9]+)/$', login_required(views.vlprint), name='vlprint'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^pdf/(?P<worksheet_id>[0-9]+)/$', login_required(views.generate_pdf), name='pdf'),
	url(r'^list_json/$', login_required(views.ListJson.as_view()), name='list_json'),
	url(r'^authorize_list/(?P<machine_type>[A|R|C])/$', login_required(views.authorize_list), name='authorize_list'),
	url(r'^authorize_results/(?P<worksheet_id>[0-9]+)/$', login_required(views.authorize_results), name='authorize_results'),
	url(r'^pending_samples/$', login_required(views.pending_samples), name='get_pending_samples'),
	url(r'^pending_envelopes/$', login_required(views.pending_envelopes), name='pending_envelopes'),
	url(r'^delete/(?P<pk>[0-9]+)/$', login_required(views.delete), name='delete'),
	url(r'^reg_info/(?P<machine_type>[A|R|C])/$', login_required(views.reg_info), name='reg_info'),
	url(r'^get_instrument_id/$', login_required(views.get_instrument_id), name='get_instrument_id'),
	url(r'^barcodes/(?P<pk>[0-9]+)/$', login_required(views.barcodes), name='barcodes'),
	#url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
import datetime as dt,json
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout as auth_logout
from django.db.models import Q

from home import utils
from samples.models import Sample, Verification
from backend.models import Appendix, Facility

# Create your views here.
@login_required
def home(request):	
	return render(request, 'home/index.html')

def quick_stats(request):
	today = dt.datetime.today()
	last_month = utils.last_month()

	last_month_filter = Q(created_at__year=last_month.get('year'), created_at__month=last_month.get('month'))
	this_month_filter = Q(created_at__year=today.year, created_at__month=today.month)
	today_filter =  Q(created_at__range=utils.today_range())
	you_filter = Q(created_by=request.user)

	you_filter2 = Q(verified_by=request.user)

	stats = {
		'samples_everyone':{
			'all':Sample.objects.all().count(),
			'last_month':Sample.objects.filter(last_month_filter).count(),
			'this_month':Sample.objects.filter(this_month_filter).count(),
			'today':Sample.objects.filter(today_filter).count()
			},
		'samples_you':{
			'all':Sample.objects.filter(you_filter).count(),
			'last_month':Sample.objects.filter(you_filter&last_month_filter).count(),
			'this_month':Sample.objects.filter(you_filter&this_month_filter).count(),
			'today':Sample.objects.filter(you_filter&today_filter).count()
			},
		'approvals_everyone':{
			'all':Verification.objects.all().count(),
			'last_month':Verification.objects.filter(last_month_filter).count(),
			'this_month':Verification.objects.filter(this_month_filter).count(),
			'today':Verification.objects.filter(today_filter).count()
			},
		'approvals_you':{
			'all':Verification.objects.filter(you_filter2).count(),
			'last_month':Verification.objects.filter(you_filter2&last_month_filter).count(),
			'this_month':Verification.objects.filter(you_filter2&this_month_filter).count(),
			'today':Verification.objects.filter(you_filter2&today_filter).count()
			}
		}
	return HttpResponse(json.dumps(stats))

def login_page(request):
	return render(request, 'home/login.html')

def login_attempt(request):
	error_message = "incorrect username or password"
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			return redirect('/')
		else:
			return render(request, 'home/login.html', {'error_message': error_message, })
	else:
		return render(request, 'home/login.html', {'error_message': error_message, })
		# Return an 'invalid login' error message.

def logout(request):
	auth_logout(request)
	next = request.GET.get('next')
	return redirect(next if next else '/')

home/templates/home/_approval_stats.html
{% load form_tags %}
{% if perms.samples.add_verification %}
<div class="row">
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">

				<div class="stat_ico color_b"><i class="ion-ios7-people"></i></div>
				<div class="stat_content">
					<span class="stat_name" style="color:#e67e22">
						Approval stats for everyone
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">						
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_everyone.all|number %>
					</span>
					<span class="stat_name">all</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_everyone.last_month|number %>
					</span>
					<span class="stat_name">last month</span>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4" >
		<div class="panel panel-default">
			<div class="stat_box" >
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_everyone.this_month|number %>
					</span>
					<span class="stat_name">this month</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_everyone.today|number %>
					</span>
					<span class="stat_name">today</span>
				</div>
			</div>
		</div>
	</div>	
							
</div>

<div class="row">
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">

				<div class="stat_ico color_b"><i class="ion-ios7-person"></i></div>
				<div class="stat_content">
					<span class="stat_name" style="color:#e67e22">
						Approval stats for you
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">						
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_you.all|number %>
					</span>
					<span class="stat_name">all</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_you.last_month|number %>
					</span>
					<span class="stat_name">last month</span>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4" >
		<div class="panel panel-default">
			<div class="stat_box" >
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_you.this_month|number %>
					</span>
					<span class="stat_name">this month</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.approvals_you.today|number %>
					</span>
					<span class="stat_name">today</span>
				</div>
			</div>
		</div>
	</div>	
							
</div>
{% endif %}

home/templates/home/_sample_stats.html
{% load form_tags %}
<div class="row">
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">

				<div class="stat_ico color_g"><i class="ion-ios7-people"></i></div>
				<div class="stat_content">
					<span class="stat_name" style="color:#ac193d">
						Samples stats for everyone
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">						
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_everyone.all|number %>
					<span class="stat_name">all</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_everyone.last_month|number %>
					</span>
					<span class="stat_name">last month</span>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4" >
		<div class="panel panel-default">
			<div class="stat_box" >
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_everyone.this_month|number %>
					</span>
					<span class="stat_name">this month</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_everyone.today|number %>
					</span>
					<span class="stat_name">today</span>
				</div>
			</div>
		</div>
	</div>	
							
</div>

{% if perms.samples %}
<div class="row">
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">

				<div class="stat_ico color_g"><i class="ion-ios7-person"></i></div>
				<div class="stat_content">
					<span class="stat_name" style="color:#ac193d">
						Samples stats for you
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">						
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_you.all|number %>
					</span>
					<span class="stat_name">all</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_you.last_month|number %>
					</span>
					<span class="stat_name">last month</span>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-4" >
		<div class="panel panel-default">
			<div class="stat_box" >
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_you.this_month|number %>
					</span>
					<span class="stat_name">this month</span>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-2 col-md-4">
		<div class="panel panel-default">
			<div class="stat_box">
				
				<div class="stat_content">
					<span class="stat_count">
						<span class="ion-loading-a" ng-if="still_loading"></span>
						<% stats.samples_you.today|number %>
					</span>
					<span class="stat_name">today</span>
				</div>
			</div>
		</div>
	</div>	
									
</div>
{% endif %}

home/templates/home/index.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/angular/angular.min.js" %}'></script>
{% endblock %}

{% block content %}
<h1>Welcome, {{ request.user.username }}</h1>
<div ng-app="vl_home" ng-controller="HomeController" class="ng-cloak">
{% include "home/_sample_stats.html" %}
{% include "home/_approval_stats.html" %}
</div>

<script type="text/javascript">
var app=angular.module('vl_home', [], function($interpolateProvider) {
    $interpolateProvider.startSymbol('<%');
    $interpolateProvider.endSymbol('%>');
 });

ctrller={};
ctrller.HomeController = function($scope,$http){
	$scope.stats = {};
	$scope.still_loading = true;
	
	$http.get("/quick_stats/").success(function(data){
		$scope.stats=data;	
		$scope.still_loading = false;	
	});

}

app.controller(ctrller);
</script>				
<style type="text/css">
.stat_name{
	text-transform: uppercase;
}

.stat_box{
	height: 70px;
}
</style>				

{% endblock content %}

home/templates/home/old.layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="UTF-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

	    <title>Viral Load</title>
	    <link rel="Shortcut Icon" href='{% static "home/images/favicon.png" %}' />

	    <link rel="stylesheet" href='{% static "home/vendor/jquery-ui/themes/base/jquery-ui.min.css" %}'>
	    <link rel="stylesheet" href='{% static "home/vendor/bootstrap/dist/css/bootstrap.min.css" %}'>	    

	    <link href='{% static "home/vendor/metisMenu/dist/metisMenu.min.css" %}' rel="stylesheet">
	    <link href='{% static "home/sb-admin-2/dist/css/timeline.css" %}' rel="stylesheet">
	    <link href='{% static "home/sb-admin-2/dist/css/sb-admin-2.css" %}' rel="stylesheet">	    
	   <!-- <link href="../bower_components/morrisjs/morris.css" rel="stylesheet"> -->
	   <link href='{% static "home/vendor/font-awesome-min/css/font-awesome.min.css" %}' rel="stylesheet" type="text/css">

	    <link rel="stylesheet" href='{% static "home/css/app.css" %}'>
	    {% block css %}
		{% endblock %}

	    <script type="text/javascript" src='{% static "home/vendor/jquery/dist/jquery.min.js" %}'></script>
	    <script type="text/javascript" src='{% static "home/vendor/bootstrap/dist/js/bootstrap.min.js" %}'></script>
	    <script type="text/javascript" src='{% static "home/vendor/jquery-ui/jquery-ui.min.js" %}'></script>
	    <script type="text/javascript" src='{% static "home/vendor/metisMenu/dist/metisMenu.min.js" %}'></script>

	    <script type="text/javascript" src='{% static "home/sb-admin-2/dist/js/sb-admin-2.js" %}'></script>

	    <script type="text/javascript" src='{% static "home/js/app.js" %}'></script>

	    {% block js %}
		{% endblock %}

	</head>

	<body>
		<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="index.html"> VIRAL LOAD TESTING</a>

            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
            	<li> 
            		<img src='{% static "home/images/ug.png" %}'  width="45" height="45">
            	</li>
 
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                       
                        <li>
                            <a href="{% url 'home_page' %}"><i class="fa fa-home fa-fw"></i> Home</a>
                        </li>
                        

                        {% if perms.samples %}

                        <li>
                            <a href="#"><i class="fa fa-folder-open fa-fw"></i> Samples<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'samples:create' %}">Create</a>
                                </li>
                                <li>
                                    <a href="{% url 'samples:list' %}">List</a>
                                </li>
                            </ul>
                            
                        </li>

                        {% endif %}

                        <li>
                            <a href="{% url 'samples:verify_list' %}"><i class="fa fa-check-square-o fa-fw"></i> Verifications</a>
                        </li>

                         {% if perms.worksheets %}

                        <li>
                            <a href="#"><i class="fa fa-flask fa-fw"></i> Lab<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Create Worksheet</a>
                                    <ul class="nav nav-third-level">
                                        <li><a href="{% url 'worksheets:create' 'A' %}">For Abbott</a></li>
                                        <li><a href="{% url 'worksheets:create' 'R' %}">For Roche CAP/CTM</a></li>
                                        <li><a href="{% url 'worksheets:create' 'C' %}">For Cobas 8800</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'worksheets:list'  %}">List Worksheets</a></li>
                                
                                <li>
                                    <a href="#">Authorize Results</a>
                                     <ul class="nav nav-third-level">
                                        <li><a href="{% url 'worksheets:authorize_list' 'A' %}">For Abbott</a></li>
                                        <li><a href="{% url 'worksheets:authorize_list' 'R' %}">For Roche CAP/CTM</a></li>
                                        <li><a href="{% url 'worksheets:authorize_list' 'C' %}">For Cobas 8800</a></li>
                                    </ul>
                                </li>
                               
                            </ul>
                            
                        </li>

                        {% endif %}

                        {% if perms.results %}

                        <li>
                            <a href="#"><i class="fa fa-file-o fa-fw"></i> Results Release<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="{% url 'results:release_list' 'A' %}">For Abbott</a></li>
                                <li><a href="{% url 'results:release_list' 'R' %}">For Roche CAP/CTM</a></li>
                                <li><a href="{% url 'results:release_list' 'C' %}">For Cobas 8800</a></li>
                            </ul>
                        </li>

                        {% endif %}

                        <li>
                            <a href="#"><i class="fa fa-copy fa-fw"></i> Reports<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Test Outcome Report</a>
                                </li>
                                <li>
                                    <a href="#">List</a>
                                </li>
                            </ul>
                            
                        </li>

                         <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input id="search_id" type="text" class="form-control" placeholder="Search...">
                                <div class="input-group-btn">
        							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        							<span class="caret"></span></button>
							        <ul class="dropdown-menu dropdown-menu-right">
    						            <li ><a class="search_link" href="{% url 'samples:list' %}" >Sample</a></li>
    						            <li ><a class="search_link" href="{% url 'samples:verify_list' %}" >Verify</a></li>
    						            <li ><a class="search_link" href="{% url 'worksheets:list' %}" >Worksheet</a></li>
                                        <li ><a class="search_link" href="{% url 'results:list' %}" >Results</a></li>
							        </ul>
      							</div><!-- /btn-group -->
                            </div>
                            <!-- /input-group -->
                        </li>   

                        <li>
                            <a href="{% url 'logout' %}"><i class="glyphicon glyphicon-log-out"></i> Logout</a>
                        </li> 
                      
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid" >
            	<div class="row">
            		<div class="col-lg-11">
                        {% block content %}
                        {% endblock %}
            		</div>
            		<div class="col-lg-1"></div>

            	</div>

                        
                   
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <script type="text/javascript">

    $(function() {
    	 $(".search_link").click(function(){
    	 	var link = $(this).attr("href");
    	 	var search_val = $("#search_id").val();
    	 	window.location.href = link+"?search_val="+search_val;
    	 	return false;
    	 	//return window.location.assign(link+"?search_val="+search_val);
    	 }); 
    });
    </script>
	</body>
</html>