api/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'api'
urlpatterns  = [
	url(r'^results/$', views.results, name='results'),
	url(r'^facilities/$', views.facilities, name='facilities'),
	url(r'^samples/$', views.samples, name='samples'),
	url(r'^update_dispatch_details/$', views.update_dispatch_details, name='update_dispatch_details'),
]

results/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from easy_pdf.views import PDFTemplateView
from .views import HelloPDFView
from . import views

app_name = 'results'
urlpatterns  = [
	url(r'^upload/(?P<worksheet_id>[0-9]+)/$', login_required(views.upload), name='upload'),
	url(r'^release_list/(?P<machine_type>[A|R|C])/$', login_required(views.release_list), name='release_list'),
	url(r'^release_results/(?P<worksheet_id>[0-9]+)/$', login_required(views.release_results), name='release_results'),
	url(r'^cobas_upload/$', login_required(views.cobas_upload), name='cobas_upload'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^worksheet/(?P<worksheet_id>[0-9]+)/$', login_required(views.worksheet_results), name='worksheet'),
	url(r'^api', login_required(views.api), name='api'),
	url(r'^anomalies/(?P<worksheet_id>[0-9]+)/$', login_required(views.get_anomalies), name='anomalies'),
	url(r'^intervene_list/$', login_required(views.intervene_list), name='intervene_list'),
	url(r'^reschedule/(?P<result_pk>[0-9]+)/$', login_required(views.reschedule), name='reschedule'),
	url(r'^authorize_sample/$', login_required(views.authorize_sample), name='authorize_sample'),
	url(r'^release_sample/$', login_required(views.release_sample), name='release_sample'),
	url(r'^print_results/(?P<result_id>[0-9]+)/(?P<worksheet_id>[0-9]+)/$', login_required(views.print_results), name='print_results'),
	#url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^hello.pdf$', HelloPDFView.as_view()),
]

viral_load2/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from home import views as home_views, session

urlpatterns = [
	url(r'^$', home_views.home, name='home_page'),
	url(r'^login/', home_views.login_page, name='login_page'),
	url(r'^login_attempt/', home_views.login_attempt, name='login_attempt'),
	url(r'^logout/', home_views.logout, name='logout'),
	url(r'^quick_stats/', home_views.quick_stats, name='quick_stats'),
	url(r'^change-password/$', auth_views.password_change, {'post_change_redirect': 'home_page'}, name='password_change'),
	url(r'^admin/', admin.site.urls),
	url(r'^samples/', include('samples.urls')),
	url(r'^worksheets/', include('worksheets.urls')),
	url(r'^results/', include('results.urls')),
	url(r'^api/', include('api.urls')),
]

worksheets/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'worksheets'
urlpatterns  = [
	url(r'^create/(?P<machine_type>[A|R|C])$', login_required(views.create), name='create'),
	url(r'^attach_samples/(?P<worksheet_id>[0-9]+)/$', login_required(views.attach_samples), name='attach_samples'),
	url(r'^show/(?P<worksheet_id>[0-9]+)/$', login_required(views.show), name='show'),
	url(r'^edit/(?P<worksheet_id>[0-9]+)/$', login_required(views.edit), name='edit'),
	url(r'^vlprint/(?P<worksheet_id>[0-9]+)/$', login_required(views.vlprint), name='vlprint'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^pdf/(?P<worksheet_id>[0-9]+)/$', login_required(views.generate_pdf), name='pdf'),
	url(r'^list_json/$', login_required(views.ListJson.as_view()), name='list_json'),
	url(r'^authorize_list/(?P<machine_type>[A|R|C])/$', login_required(views.authorize_list), name='authorize_list'),
	url(r'^authorize_results/(?P<worksheet_id>[0-9]+)/$', login_required(views.authorize_results), name='authorize_results'),
	url(r'^pending_samples/$', login_required(views.pending_samples), name='get_pending_samples'),
	url(r'^pending_envelopes/$', login_required(views.pending_envelopes), name='pending_envelopes'),
	url(r'^delete/(?P<pk>[0-9]+)/$', login_required(views.delete), name='delete'),
	url(r'^reg_info/(?P<machine_type>[A|R|C])/$', login_required(views.reg_info), name='reg_info'),
	url(r'^get_instrument_id/$', login_required(views.get_instrument_id), name='get_instrument_id'),
	url(r'^barcodes/(?P<pk>[0-9]+)/$', login_required(views.barcodes), name='barcodes'),
	#url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

results/models.py
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

import samples.models as samples
import backend.models as backend
import worksheets.models as worksheets

# Create your models here.

#track 
class Result(models.Model):
	METHOD_CHOICES = ( ('A', 'Abbott Real time HIV-1 PCR'), ('R', 'HIV-1 RNA PCR Roche'), ('C', 'HIV-1 RNA PCR Roche'))
	sample = models.OneToOneField(samples.Sample, on_delete=models.CASCADE)
	repeat_test = models.PositiveSmallIntegerField(default=2,choices=( (1, 'YES'),(2, 'NO'), (3, 'PROPOSED') ))
	result1 = models.TextField()
	result2 = models.TextField()
	result3 = models.TextField()
	result4 = models.TextField()
	result5 = models.TextField()

	suppressed = models.PositiveSmallIntegerField(default=3,choices=( (1, 'YES'),(2, 'NO'), (3, 'UNKNOWN') ))
	result_numeric = models.IntegerField(null=True)
	printed = models.IntegerField(null=True)
	result_alphanumeric = models.TextField()
	method = models.CharField(max_length=1, null=True, choices=METHOD_CHOICES)
	result_upload_date = models.DateTimeField(null=True)
	test_date = models.DateTimeField(null=True)

	test_by = models.ForeignKey(User,null=True, related_name='test_by')

	authorised = models.BooleanField(default=False)
	authorised_by = models.ForeignKey(User, related_name='authorised_by', null=True)
	authorised_at = models.DateTimeField(null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.sample.form_number

	class Meta:
		db_table = 'vl_results'
	

#track sample sample printing and dispatch
class ResultsQC(models.Model):
	result = models.OneToOneField(Result, on_delete=models.CASCADE)
	released = models.BooleanField(default=False)
	released_by = models.ForeignKey(User, related_name='released_by', null=True)
	released_at = models.DateTimeField(null=True)
	comments = models.TextField(null=True)

	class Meta:
		db_table = 'vl_results_qc'

class ResultsDispatch(models.Model):
	sample = models.OneToOneField(samples.Sample, on_delete=models.CASCADE)
	dispatch_type = models.CharField(max_length=1, null=True, choices=( ('P', 'Printed'),('D', 'Downloaded') ))
	dispatch_date = models.DateTimeField(null=True)
	dispatched_by = models.CharField(max_length=128, null=True)

	class Meta:
		db_table = 'vl_results_dispatch'

#track worksheets whose results have been uploaded
class WorksheetResultsUpload(models.Model):
	worksheet = models.ForeignKey(worksheets.Worksheet)
	results_file = models.FileField(upload_to='results')
	multiplier = models.IntegerField(default=1)
	upload_date = models.DateTimeField(auto_now_add=True)
	uploaded_by = models.ForeignKey(User, related_name='uploaded_by')

	def clean(self):
		file_name = self.results_file.name		
		if self.worksheet == 'R' and file_name.endswith('.csv') is not True:
			raise ValidationError(_("Expecting a csv file"))
		if self.worksheet == 'A' and file_name.endswith('.txt') is not True:
			raise ValidationError(_("Expecting a txt file"))

	class Meta:
		db_table = 'vl_worksheet_results_uploads'	

class CobasResultsUpload(models.Model):
	reference_number = models.CharField(max_length=128, null=True)
	results_file = models.FileField(upload_to='results')
	multiplier = models.IntegerField(default=1)
	upload_date = models.DateTimeField(auto_now_add=True)
	cobas_uploaded_by = models.ForeignKey(User, related_name='cobas_uploaded_by')

	def clean(self):
		file_name = self.results_file.name		
		if file_name.endswith('.csv') is not True:
			raise ValidationError(_("Expecting a csv file"))

	class Meta:
		db_table = 'vl_cobas_results_uploads'	

worksheets/models.py
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from samples.models import Sample

import backend.models as backend

#'awaiting_results','has_results','passed_lab_qc','passed_data_qc'

# Create your models here.
MACHINE_TYPES = ( ('A', 'Abbott'), ('R', 'Roche CAP/CTM'), ('C', 'Cobas 8800') )
STAGE_CHOICES = ( (1, 'awaiting_results'),(2, 'has_results'), (3, 'passed_lab_qc'), (4, 'passed_data_qc') )

class Worksheet(models.Model):
	
	samples = models.ManyToManyField(Sample, through='WorksheetSample')
	worksheet_reference_number = models.CharField(max_length=128)
	machine_type = models.CharField(max_length=1, choices=MACHINE_TYPES)
	sample_type = models.CharField(max_length=1, choices=Sample.SAMPLE_TYPES)
	sample_prep = models.CharField(max_length=64,null=True, blank=True)
	sample_prep_expiry_date = models.DateField(null=True, blank=True)
	bulk_lysis_buffer = models.CharField(max_length=64, null=True, blank=True)
	bulk_lysis_buffer_expiry_date = models.DateField(null=True, blank=True)
	control = models.CharField(max_length=64, null=True, blank=True)
	control_expiry_date = models.DateField(null=True, blank=True)
	calibrator = models.CharField(max_length=64, null=True, blank=True)
	calibrator_expiry_date = models.DateField(null=True, blank=True)
	include_calibrators = models.BooleanField(default=False)
	amplication_kit = models.CharField(max_length=64, null=True, blank=True)
	amplication_kit_expiry_date = models.DateField(null=True, blank=True)
	assay_date = models.DateTimeField()
	generated_by = models.ForeignKey(User, related_name='generated_by')
	worksheet_updated_by = models.ForeignKey(User, related_name='worksheet_updated_by', null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	stage = models.PositiveSmallIntegerField(choices=STAGE_CHOICES, default=1)
	worksheet_medical_lab = models.ForeignKey(backend.MedicalLab, related_name='worksheet_medical_lab', default=1)

	class Meta:
		db_table = 'vl_worksheets'


#Attaching samples to work sheet
class WorksheetSample(models.Model):
	worksheet = models.ForeignKey(Worksheet, on_delete=models.CASCADE)
	sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
	stage = models.PositiveSmallIntegerField(choices=STAGE_CHOICES, default=1)
	sample_run = models.PositiveSmallIntegerField(default=1)
	instrument_id = models.CharField(max_length=64, null=True, blank=True)
	rack_id = models.CharField(max_length=64, null=True, blank=True)

	class Meta:
		db_table = 'vl_worksheet_samples'


class WorksheetPrinting(models.Model):
	worksheet = models.OneToOneField(Worksheet, on_delete=models.CASCADE)
	worksheet_printed_by = models.ForeignKey(User, related_name='worksheet_printed_by')
	printed_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'vl_worksheet_printing'

worksheets/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Worksheet
from samples.models import Sample
from home import utils


class WorksheetForm(forms.ModelForm):
	class Meta:
		model = Worksheet
		fields = (
			'machine_type',
			'sample_type',
			'sample_prep',
			'sample_prep_expiry_date',
			'bulk_lysis_buffer',
			'bulk_lysis_buffer_expiry_date',
			'control',
			'control_expiry_date',
			'calibrator',
			'calibrator_expiry_date',
			'include_calibrators',
			'amplication_kit',
			'amplication_kit_expiry_date',
			'assay_date',
		)

		widgets = {
			'machine_type': forms.Select(attrs=utils.ATTRS2),
			'sample_type': forms.Select(attrs=utils.ATTRS2),
			'sample_prep': forms.TextInput(attrs=utils.ATTRS),
			'sample_prep_expiry_date': forms.DateInput(attrs=utils.ATTRS_DATE),
			'bulk_lysis_buffer': forms.TextInput(attrs=utils.ATTRS_OPTIONAL),
			'bulk_lysis_buffer_expiry_date': forms.DateInput(attrs=utils.ATTRS_DATE),
			'control': forms.TextInput(attrs=utils.ATTRS),
			'control_expiry_date': forms.DateInput(attrs=utils.ATTRS_DATE),
			'calibrator': forms.TextInput(attrs=utils.ATTRS),
			'calibrator_expiry_date': forms.DateInput(attrs=utils.ATTRS_DATE),
			'amplication_kit': forms.TextInput(attrs=utils.ATTRS),
			'amplication_kit_expiry_date': forms.DateInput(attrs=utils.ATTRS_DATE),
		}

		labels = {
			'control': _('Control lot'),
			'calibrator': _('Calibrator lot'),
			'amplication_kit': _('Amplication kit lot'),
		}

class AttachSamplesForm(forms.ModelForm):
	samples = forms.ModelMultipleChoiceField(
					queryset=Sample.objects.values('id','form_number').filter(
						verified=True, 
						in_worksheet=False).order_by('created_at')[:80],
					widget=forms.CheckboxSelectMultiple())
	class Meta:
		model = Worksheet
		fields = ('samples',)

worksheets/templates/worksheets/authorize_list.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/datatables/media/css/dataTables.jqueryui.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/datatables/media/js/jquery.dataTables.js" %}'></script>
{% endblock %}

{% block content %}	

<div class="page-title">Worksheets :: {{ machine_type }}</div>

<div class="panel panel-default">
	<ul id="tabs_a" class="nav nav-tabs">
	    <li {% if request.GET.tab != 'authorised' %}class='active'{% endif %}>
	    	<a href="?tab=pending">Pending</a>
	    </li>
	    <li {% if request.GET.tab == 'authorised' %}class='active'{% endif %}>
	    	<a href="?tab=authorised">Authorised</a>
	    </li>
	</ul>
	<div class="tab-content">
	<table class='table table-bordered table-striped table table-condensed' id='tab_id'>
		<thead>
			<tr>
				<th>Worksheet Ref Number</th>
				<th>Machine Type</th>
				<th>Sample Type</th>
				<th>Date Created</th>
			</tr>
		</thead>
		<tbody>
			{% for worksheet in worksheets %}
			<tr>
				<td><a href="{% url 'worksheets:authorize_results' worksheet.id %}">{{ worksheet.worksheet_reference_number }}</a></td>
				<td>{{ worksheet.get_machine_type_display }}</td>
				<td>{{ worksheet.get_sample_type_display }}</td>
				<td>{{ worksheet.created_at | date:"Y-m-d" }}</td>
			</tr>
			{% endfor %}
			
		</tbody>
	</table>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var oTable = $('#tab_id').dataTable({
		"processing": true,
		"paging":false,
		"order": [[ 0, "desc" ]],
	});
});
</script>

{% endblock %}

worksheets/templates/worksheets/create.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/datatables/media/css/dataTables.jqueryui.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/moment/min/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/combodate/src/combodate.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/datatables/media/js/jquery.dataTables.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/angular/angular.min.js" %}'></script>
{% endblock %}

{% block content %}	
	<span class="page-title">create worksheet</span>		
	<div class="panel panel-default" ng-app="worksheet_samples" ng-controller="worksheetSamplesController">
		<div class="panel-body">
			
			<form action="{% url 'worksheets:create' machine_type %}" method="post" role="form">
				{% csrf_token %}
				<div class="row">
					<div class="form-group col-md-5">
						<label for="id_wrn">Worksheet Ref Number:</label>
						<input class="form-control input-sm w-md" id="id_wrn" maxlength="64" name="wrn" readonly="true" type="text" placeholder="this will be generated after saving">
						
					</div>

					<div class="form-group col-md-4">
						<div id="log"></div>
						{{ form.machine_type.label_tag }}
						{{ form.machine_type.errors }}
						{{ form.machine_type }}
					</div>

					<div class="form-group col-md-3">
						{{ form.sample_type.label_tag }}
						{{ form.sample_type.errors }}
						{{ form.sample_type }}
					</div>
				</div>
				
				<div class="row">
					<div class="form-group col-md-5">
						{% if machine_type == 'R' %}
							<label for="id_sample_prep">HI2CAP</label>
						{% elif machine_type == 'C' %}
							<label for="id_sample_prep">Cobas HIV 1</label>
						{% else %}
							{{ form.sample_prep.label_tag }}
						{% endif %}
						
						{{ form.sample_prep.errors }}
						{{ form.sample_prep }}
					</div>

					<div class="form-inline col-md-4">
						{% if machine_type == 'R' %}
							<label for="id_sample_prep">HI2CAP expiry date</label>
						{% elif machine_type == 'C' %}
							<label for="id_sample_prep">Cobas HIV 1 expiry date</label>
						{% else %}
							{{ form.sample_prep_expiry_date.label_tag }}
						{% endif %}
						
						{{ form.sample_prep_expiry_date.errors }}
						<br>{{ form.sample_prep_expiry_date }}
					</div>
				</div>

				{% if machine_type != 'C' %}
				<div class="row">
					<div class="form-group col-md-5">
						{{ form.bulk_lysis_buffer.label_tag }}
						{{ form.bulk_lysis_buffer.errors }}
						{{ form.bulk_lysis_buffer }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.bulk_lysis_buffer_expiry_date.label_tag }}
						{{ form.bulk_lysis_buffer_expiry_date.errors }}
						<br>{{ form.bulk_lysis_buffer_expiry_date }}
					</div>
				</div>
				{% endif %}
				

				{% if machine_type == 'A' %}
				<div class="row">
					<div class="form-group col-md-5	">
						{{ form.control.label_tag }}
						{{ form.control.errors }}
						{{ form.control }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.control_expiry_date.label_tag }}
						{{ form.control_expiry_date.errors }}
						<br>{{ form.control_expiry_date }}
					</div>
				</div>

				<div class="row">
					<div class="form-group col-md-5">
						{{ form.calibrator.label_tag }}
						{{ form.calibrator.errors }}
						{{ form.calibrator }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.calibrator_expiry_date.label_tag }}
						{{ form.calibrator_expiry_date.errors }}
						<br>{{ form.calibrator_expiry_date }}
					</div>

					<div class="form-group col-md-3">
						<br>	
						{{ form.include_calibrators.errors }}
						{{ form.include_calibrators }}
						{{ form.include_calibrators.label_tag }}				
					</div>
				</div>

				<div class="row">
					<div class="form-group col-md-5">
						{{ form.amplication_kit.label_tag }}
						{{ form.amplication_kit.errors }}
						{{ form.amplication_kit }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.amplication_kit_expiry_date.label_tag }}
						{{ form.amplication_kit_expiry_date.errors }}
						<br>{{ form.amplication_kit_expiry_date }}
					</div>
				</div>

				{% endif %}

				<div class="form-inline">
					{{ form.assay_date.label_tag }}
					{{ form.assay_date.errors }}
					<br>{{ form.assay_date }}
				</div>
				<br>{{ userid }}

				<br><input id="id_submit" type='submit' value='save and attach samples' class="btn btn-danger btn-submit "> 
				
			</form>
		</div>
	</div>
	<style type="text/css">
	.form-group,.form-inline{
		margin-bottom: 0px;
	}
	</style>
	
	<script type="text/javascript">
	var date_now = new Date();
	var yr_now = date_now.getFullYear();
	$( function() {
		$("#id_submit").click(function(){
			var sample_type = $("#id_sample_type").val();
			if(sample_type==""){
				alert("please select sample type");
				return false;
			}else{
				return true;
			}
		})
		$(".date").combodate({
    		format: "YYYY-MM-DD",
    		template: "D MMM YYYY",
    		customClass: "form-control input-sm",
    		maxYear: yr_now+30,
    		minYear: yr_now-1,
    		yearDescending: false,    		
    	});

    	$("#id_assay_date").combodate({
    		format: "YYYY-MM-DD",
    		template: "D MMM YYYY",
    		customClass: "form-control input-sm",
    		maxYear: yr_now+30,
    		minYear: yr_now-1,
    		yearDescending: false, 
    		value: new Date(),
    	});

    	$("#id_machine_type").attr('readonly','true');

    	/*var oTable = $('#samples-table').dataTable({
			"processing": true,
		});*/
	});

	/*$(".lab-tabs").on('click',function(){
		$(this).addClass('active');
		console.log("dedere");
	});
*/

	</script>
{% endblock %}

worksheets/templates/worksheets/reg_info.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/datatables/media/css/dataTables.jqueryui.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/moment/min/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/combodate/src/combodate.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/datatables/media/js/jquery.dataTables.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/angular/angular.min.js" %}'></script>
{% endblock %}

{% block content %}	
	<span class="page-title">capture regimen information</span>		
	<div class="panel panel-default" ng-app="worksheet_samples" ng-controller="worksheetSamplesController">
		<div class="panel-body">
			
			<form action="{% url 'worksheets:reg_info' machine_type %}" method="post" role="form">
				{% csrf_token %}
				<div class="row">
					<div class="form-group col-md-5">
						<div id="log"></div>
						{{ form.machine_type.label_tag }}
						{{ form.machine_type.errors }}
						{{ form.machine_type }}
					</div>
				</div>
				
				<div class="row">
					<div class="form-group col-md-5">
						{% if machine_type == 'R' %}
							<label for="id_sample_prep">HI2CAP</label>
						{% elif machine_type == 'C' %}
							<label for="id_sample_prep">Cobas HIV 1</label>
						{% else %}
							{{ form.sample_prep.label_tag }}
						{% endif %}
						
						{{ form.sample_prep.errors }}
						{{ form.sample_prep }}
					</div>

					<div class="form-inline col-md-4">
						{% if machine_type == 'R' %}
							<label for="id_sample_prep">HI2CAP expiry date</label>
						{% elif machine_type == 'C' %}
							<label for="id_sample_prep">Cobas HIV 1 expiry date</label>
						{% else %}
							{{ form.sample_prep_expiry_date.label_tag }}
						{% endif %}
						
						{{ form.sample_prep_expiry_date.errors }}
						<br>{{ form.sample_prep_expiry_date }}
					</div>
				</div>

				{% if machine_type != 'C' %}
				<div class="row">
					<div class="form-group col-md-5">
						{{ form.bulk_lysis_buffer.label_tag }}
						{{ form.bulk_lysis_buffer.errors }}
						{{ form.bulk_lysis_buffer }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.bulk_lysis_buffer_expiry_date.label_tag }}
						{{ form.bulk_lysis_buffer_expiry_date.errors }}
						<br>{{ form.bulk_lysis_buffer_expiry_date }}
					</div>
				</div>
				{% endif %}
				

				{% if machine_type == 'A' %}
				<div class="row">
					<div class="form-group col-md-5	">
						{{ form.control.label_tag }}
						{{ form.control.errors }}
						{{ form.control }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.control_expiry_date.label_tag }}
						{{ form.control_expiry_date.errors }}
						<br>{{ form.control_expiry_date }}
					</div>
				</div>

				<div class="row">
					<div class="form-group col-md-5">
						{{ form.calibrator.label_tag }}
						{{ form.calibrator.errors }}
						{{ form.calibrator }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.calibrator_expiry_date.label_tag }}
						{{ form.calibrator_expiry_date.errors }}
						<br>{{ form.calibrator_expiry_date }}
					</div>
				</div>

				<div class="row">
					<div class="form-group col-md-5">
						{{ form.amplication_kit.label_tag }}
						{{ form.amplication_kit.errors }}
						{{ form.amplication_kit }}
					</div>

					<div class="form-inline col-md-4">
						{{ form.amplication_kit_expiry_date.label_tag }}
						{{ form.amplication_kit_expiry_date.errors }}
						<br>{{ form.amplication_kit_expiry_date }}
					</div>
				</div>

				{% endif %}

				
				<br><input type='submit' value='save' class="btn btn-danger btn-submit "> 
				
			</form>
		</div>
	</div>
	<style type="text/css">
	.form-group,.form-inline{
		margin-bottom: 0px;
	}
	</style>
	<script type="text/javascript">
	var date_now = new Date();
	var yr_now = date_now.getFullYear();
	$( function() {
		$(".date").combodate({
    		format: "YYYY-MM-DD",
    		template: "D MMM YYYY",
    		customClass: "form-control input-sm",
    		maxYear: yr_now+30,
    		minYear: yr_now-1,
    		yearDescending: false,    		
    	});

    	$("#id_assay_date").combodate({
    		format: "YYYY-MM-DD",
    		template: "D MMM YYYY",
    		customClass: "form-control input-sm",
    		maxYear: yr_now+30,
    		minYear: yr_now-1,
    		yearDescending: false, 
    		value: new Date(),
    	});

    	$("#id_machine_type").attr('readonly','true');

    	/*var oTable = $('#samples-table').dataTable({
			"processing": true,
		});*/
	});

	/*$(".lab-tabs").on('click',function(){
		$(this).addClass('active');
		console.log("dedere");
	});
*/

	</script>
{% endblock %}