api/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'api'
urlpatterns  = [
	url(r'^results/$', views.results, name='results'),
	url(r'^facilities/$', views.facilities, name='facilities'),
	url(r'^samples/$', views.samples, name='samples'),
	url(r'^update_dispatch_details/$', views.update_dispatch_details, name='update_dispatch_details'),
]

samples/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views, data_table_views

app_name = 'samples'

urlpatterns  = [
	#url(r'^$', views.index, name='list_samples'),
	url(r'^create/$', login_required(views.create), name='create'),
	url(r'^get_facility/(?P<form_number>[\w-]+)/$', login_required(views.get_facility), name='get_facility'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^list_json$', login_required(data_table_views.ListJson.as_view()), name='list_json'),
	url(r'^show/(?P<sample_id>[0-9]+)$', login_required(views.show), name='show'),
	url(r'^edit/(?P<sample_id>[0-9]+)$', login_required(views.edit), name='edit'),
	url(r'^verify_list/$', login_required(views.verify_list), name='verify_list'),
	url(r'^verify/(?P<sample_id>[0-9]+)/$', login_required(views.verify), name='verify'),
	url(r'^verify_envelope/(?P<envelope_id>[0-9]+)/$', login_required(views.verify_envelope), name='verify_envelope'),
	url(r'^save_verify/$', login_required(views.save_verify), name='save_verify'),
	url(r'^verify_list_json$', login_required(data_table_views.VerifyListJson.as_view()), name='verify_list_json'),
	url(r'^get_district_hub/(?P<facility_id>[0-9]+)/$', login_required(views.get_district_hub), name='get_district_hub'),
	url(r'^patient_history/(?P<facility_id>[0-9]+)/$', login_required(views.pat_hist), name='pat_hist'),
	url(r'^clinicians/(?P<facility_id>[0-9]+)/$', login_required(views.clinicians), name='clinicians'),
	url(r'^lab_techs/(?P<facility_id>[0-9]+)/$', login_required(views.lab_techs), name='lab_techs'),
	url(r'^release_rejects/$', login_required(views.release_rejects), name='release_rejects'),
	url(r'^released_rejects/$', login_required(views.released_rejects), name='released_rejects'),
	url(r'^intervene_list/$', login_required(views.intervene_list), name='intervene_list'),

	url(r'^vl_list/$', login_required(data_table_views.vl_list), name="vl_list"),
	url(r'^vl_list/data/$', login_required(data_table_views.vl_list_data), name="vl_list_data"),

	url(r'^search/$', login_required(views.search), name='search'),

	url(r'^envelope_list/$', login_required(views.envelope_list), name="envelope_list"),
	url(r'^envelope_list_json/$', login_required(data_table_views.envelope_list_json), name='envelope_list_json'),
	url(r'^generate_forms/$', login_required(views.generate_forms), name="generate_forms"),
	url(r'^forms/$', login_required(views.forms), name="forms"),
	url(r'^edit_dispatch/(?P<dispatch_id>[0-9]+)/$', login_required(views.edit_dispatch), name="edit_dispatch"),
	url(r'^reverse_approval/(?P<verification_id>[0-9]+)/$', login_required(views.reverse_approval), name="reverse_approval"),
	url(r'^download/(?P<path>.*)$',login_required(views.download), name="download"),
	url(r'^reports/$',login_required(views.reports), name="reports"),
	url(r'^print_rejects/(?P<sample_id>[0-9]+)/$', login_required(views.print_rejects), name='print_rejects'),
]

viral_load2/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from home import views as home_views, session

urlpatterns = [
	url(r'^$', home_views.home, name='home_page'),
	url(r'^login/', home_views.login_page, name='login_page'),
	url(r'^login_attempt/', home_views.login_attempt, name='login_attempt'),
	url(r'^logout/', home_views.logout, name='logout'),
	url(r'^quick_stats/', home_views.quick_stats, name='quick_stats'),
	url(r'^change-password/$', auth_views.password_change, {'post_change_redirect': 'home_page'}, name='password_change'),
	url(r'^admin/', admin.site.urls),
	url(r'^samples/', include('samples.urls')),
	url(r'^worksheets/', include('worksheets.urls')),
	url(r'^results/', include('results.urls')),
	url(r'^api/', include('api.urls')),
]

samples/models.py
from __future__ import unicode_literals
from decimal import * 
from django.db import models
from django.contrib.auth.models import User
import backend.models as backend

# Create your models here.

#hold records of forms dispatched to facilities
class ClinicalRequestFormsDispatch(models.Model):
	facility = models.ForeignKey(backend.Facility, on_delete=models.CASCADE)
	ref_number =  models.CharField(max_length=64, null=True)
	dispatched_at = models.DateTimeField()
	dispatched_by = models.ForeignKey(User)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'vl_forms_dispatch'
		verbose_name_plural = 'Forms Dispatch'


#hold the form numbers
class ClinicalRequestForm(models.Model):
	form_number = models.CharField(max_length=128, unique=True)
	dispatch = models.ForeignKey(ClinicalRequestFormsDispatch, on_delete=models.CASCADE, null=True)
	received_back = models.BooleanField(default=False)
	
	class Meta:
		db_table = 'vl_forms'
		verbose_name_plural = 'Forms'

class Clinician(models.Model):
	facility = models.ForeignKey(backend.Facility)
	cname = models.CharField(max_length=128)
	cphone = models.CharField(max_length=64, null=True, blank=True)
	class Meta:
		db_table = 'vl_clinicians'
		unique_together = ('facility', 'cname')

class LabTech(models.Model):
	facility = models.ForeignKey(backend.Facility)
	lname = models.CharField(max_length=128)
	lphone = models.CharField(max_length=64, null=True, blank=True)
	class Meta:
		db_table = 'vl_lab_techs'
		unique_together = ('facility', 'lname')	

#hold patient records that later on link to the samples
class Patient(models.Model):
	GENDER_CHOICES = (
		('M', 'Male'),
		('F', 'Female'),
		('X', 'Missing Gender'),
		('L', 'Left Blank')
	)
	unique_id = models.CharField(max_length=128)
	name = models.CharField(max_length=128,null=True, blank=True)
	hep_number = models.CharField(max_length=64, null=True, blank=True)
	other_id = models.CharField(max_length=64, null=True, blank=True)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
	dob = models.DateField(null=True, blank=True)
	created_by = models.ForeignKey(User)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'vl_patients'

class PatientPhone(models.Model):
	patient = models.ForeignKey(Patient)
	phone = models.CharField(max_length=16, null=True, blank=True)

	class Meta:
		db_table = 'vl_patient_phones'


class Envelope(models.Model):
	envelope_number = models.CharField(max_length=10)
	stage = models.PositiveSmallIntegerField(choices=((1,'not_verified'), (2, 'verified'), (3, 'in_worksheet')), default=1)
	sample_type = models.CharField(max_length=1, choices=( ('P', 'Plasma'), ('D', 'DBS') ), default='')
	sample_medical_lab = models.ForeignKey(backend.MedicalLab,related_name='sample_medical_lab', default=1)
	created_at = models.DateTimeField(auto_now_add=True)

	# def __init__(self):
	# 	return self.envelope_number

	class Meta:
		db_table = 'vl_envelopes'

class PreliminaryFindings(models.Model):
	YES_NO_CHOICES = ( ('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank') )
	POSITIVE_NEGATIVE = ( (1, 'Positive'), (2, 'Negative') )
	WHETHER_COINFECTED_HIV = ((1,'HBV/HIV'))
	patient = models.ForeignKey(Patient)
	hbeag_results = models.PositiveSmallIntegerField(choices=POSITIVE_NEGATIVE, null=True, blank=True)
	hiv_coinfected = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	hiv_hcv_coinfected = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	hiv_hcv_tb_coinfected = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	hep_other_coinfections = models.CharField(max_length=128,null=True, blank=True)
	alt_value_1 = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	alt_value_2 = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	alt_value_3 = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	ast_value_1 = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	ast_value_2 = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	ast_value_3 = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	alt_value_normal_range = models.CharField(max_length=128,null=True, blank=True)
	platelet_count = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	platelet_normal_range = models.CharField(max_length=128,null=True, blank=True)
	ast_value_normal_range = models.CharField(max_length=128,null=True, blank=True)
	fetal_protein_value = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	fetal_protein_value_normal_range = models.CharField(max_length=128,null=True, blank=True)
	prem_other_findings= models.CharField(max_length=128,null=True, blank=True)
	ast_plt_ratio_greater_than_2 = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	serum_creatinine = models.DecimalField(max_digits=5, decimal_places = 2, null=True, blank=True)
	serum_creatinine_normal_range = models.CharField(max_length=128,null=True, blank=True)

	class Meta:
		db_table = 'vl_patient_preliminary_findings'

class PatientTreatmentIndication(models.Model):
	patient = models.ForeignKey(Patient)
	treatment_indication = models.ForeignKey(backend.Appendix, related_name='treatment_indication', null=True, blank=True)

	class Meta:
		db_table = 'vl_patient_treatment_indication'

class Sample(models.Model):
	YES_NO_CHOICES = ( ('Y', 'Yes'), ('N', 'No'), ('L', 'Left Blank') )
	SAMPLE_TYPES = ( ('P', 'Plasma'), ('D', 'DBS') )
	DRUG_NAMES = ( (1, 'Tenofovir'), (2, 'Entecavir') )
	TX_DURATION_CHOICES = ( (1, '6 months -< 1yr'), (2, '1 -< 2yrs'), (3, '2 -< 5yrs'), (4, '5yrs and above'), (5, 'Left Blank') )
	WHO_STAGES = ((1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'))
	TX_CARE_APPROACHES = ((1, 'FBIM'), (2, 'FBG'), (3, 'FTDR'), (4, 'CDDP'), (5, 'CCLAD'))
	INDICATION_FOR_VL = ( (1, 'Routing Monitoring'), (2, 'Treatment Initiation') )
	patient = models.ForeignKey(Patient)
	patient_unique_id = models.CharField(max_length=128)
	locator_category = models.CharField(max_length=1, choices=( ('V', 'V'), ('R', 'R') ))
	envelope = models.ForeignKey(Envelope)
	locator_position = models.CharField(max_length=4)
	vl_sample_id = models.CharField(max_length=128, unique=True, null=True, blank=True)
	form_number = models.CharField(max_length=64, unique=True)
	facility = models.ForeignKey(backend.Facility)
	current_regimen = models.ForeignKey(backend.Appendix, related_name='current_regimen', null=True, blank=True)
	other_regimen = models.CharField(max_length=128, null=True, blank=True)
	anc_number = models.CharField(max_length=64, null=True, blank=True) #anc number for pregnant women	
	active_tb_status = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	treatment_duration = models.PositiveSmallIntegerField(choices=TX_DURATION_CHOICES, null=True, blank=True)	
	is_study_sample = models.BooleanField(default=False)
	current_who_stage = models.PositiveSmallIntegerField(choices=WHO_STAGES, null=True, blank=True)
	viral_load_testing = models.ForeignKey(backend.Appendix, related_name='viral_load_testing',null=True, blank=True)
	treatment_indication_other = models.CharField(max_length=64, null=True, blank=True)
	treatment_line = models.ForeignKey(backend.Appendix, related_name='treatment_line',null=True, blank=True)
	failure_reason = models.ForeignKey(backend.Appendix, related_name='failure_reason', null=True, blank=True)
	tb_treatment_phase = models.ForeignKey(backend.Appendix, related_name='tb_treatment_phase', null=True, blank=True)
	arv_adherence = models.ForeignKey(backend.Appendix, related_name='arv_adherence', null=True, blank=True)
	treatment_care_approach = models.PositiveSmallIntegerField(choices=TX_CARE_APPROACHES, null=True, blank=True)
	lab_tech = models.ForeignKey(LabTech, null=True, blank=True)
	
	verified = models.BooleanField(default=False)
	in_worksheet = models.BooleanField(default=False)
	created_by = models.ForeignKey(User, related_name='created_by')
	updated_by = models.ForeignKey(User, related_name='updated_by', null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	clinician_request_date = models.DateField(null=True)
	is_patient_on_treatment = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	treatment_initiation_date = models.DateField(null=True, blank=True)
	current_drug_name = models.PositiveSmallIntegerField(choices=DRUG_NAMES, null=True, blank=True)
	pregnant = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	breast_feeding = models.CharField(max_length=1, choices=YES_NO_CHOICES, null=True, blank=True)
	reason_for_vl = models.PositiveSmallIntegerField(choices=INDICATION_FOR_VL, null=True, blank=True)
	last_test_date = models.DateField(null=True, blank=True)
	last_value = models.CharField(max_length=64, null=True, blank=True)
	last_sample_type = models.CharField(max_length=1, choices=SAMPLE_TYPES, null=True, blank=True)
	clinician = models.ForeignKey(Clinician, null=True, blank=True)
	date_collected = models.DateField(null=True, blank=True)
	date_received = models.DateField()
	sample_type = models.CharField(max_length=1, choices=SAMPLE_TYPES)
	def __str__(self):
		return self.form_number
	
	class Meta:
		db_table = 'vl_samples'
		unique_together = ('locator_category', 'envelope', 'locator_position')

class DrugResistanceRequest(models.Model):
	sample = models.OneToOneField(Sample, on_delete=models.CASCADE)
	body_weight = models.PositiveSmallIntegerField(null=True, blank=True)
	patient_on_rifampicin = models.CharField(max_length=1, choices=( ('Y', 'Yes'), ('N', 'No'),), null=True, blank=True)

	class Meta:
		db_table = 'vl_drug_resistance_requests'

worksheets/models.py
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from samples.models import Sample

import backend.models as backend

#'awaiting_results','has_results','passed_lab_qc','passed_data_qc'

# Create your models here.
MACHINE_TYPES = ( ('A', 'Abbott'), ('R', 'Roche CAP/CTM'), ('C', 'Cobas 8800') )
STAGE_CHOICES = ( (1, 'awaiting_results'),(2, 'has_results'), (3, 'passed_lab_qc'), (4, 'passed_data_qc') )

class Worksheet(models.Model):
	
	samples = models.ManyToManyField(Sample, through='WorksheetSample')
	worksheet_reference_number = models.CharField(max_length=128)
	machine_type = models.CharField(max_length=1, choices=MACHINE_TYPES)
	sample_type = models.CharField(max_length=1, choices=Sample.SAMPLE_TYPES)
	sample_prep = models.CharField(max_length=64,null=True, blank=True)
	sample_prep_expiry_date = models.DateField(null=True, blank=True)
	bulk_lysis_buffer = models.CharField(max_length=64, null=True, blank=True)
	bulk_lysis_buffer_expiry_date = models.DateField(null=True, blank=True)
	control = models.CharField(max_length=64, null=True, blank=True)
	control_expiry_date = models.DateField(null=True, blank=True)
	calibrator = models.CharField(max_length=64, null=True, blank=True)
	calibrator_expiry_date = models.DateField(null=True, blank=True)
	include_calibrators = models.BooleanField(default=False)
	amplication_kit = models.CharField(max_length=64, null=True, blank=True)
	amplication_kit_expiry_date = models.DateField(null=True, blank=True)
	assay_date = models.DateTimeField()
	generated_by = models.ForeignKey(User, related_name='generated_by')
	worksheet_updated_by = models.ForeignKey(User, related_name='worksheet_updated_by', null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	stage = models.PositiveSmallIntegerField(choices=STAGE_CHOICES, default=1)
	worksheet_medical_lab = models.ForeignKey(backend.MedicalLab, related_name='worksheet_medical_lab', default=1)

	class Meta:
		db_table = 'vl_worksheets'


#Attaching samples to work sheet
class WorksheetSample(models.Model):
	worksheet = models.ForeignKey(Worksheet, on_delete=models.CASCADE)
	sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
	stage = models.PositiveSmallIntegerField(choices=STAGE_CHOICES, default=1)
	sample_run = models.PositiveSmallIntegerField(default=1)
	instrument_id = models.CharField(max_length=64, null=True, blank=True)
	rack_id = models.CharField(max_length=64, null=True, blank=True)

	class Meta:
		db_table = 'vl_worksheet_samples'


class WorksheetPrinting(models.Model):
	worksheet = models.OneToOneField(Worksheet, on_delete=models.CASCADE)
	worksheet_printed_by = models.ForeignKey(User, related_name='worksheet_printed_by')
	printed_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'vl_worksheet_printing'

samples/templates/samples/edit_dispatch.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/select2/dist/css/select2.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/select2/dist/js/select2.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/moment/min/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/combodate/src/combodate.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/angular/angular.min.js" %}'></script>
{% endblock %}


{% block content %}	

<div class="page-title">generate request forms</div>
<div class="panel panel-default">
<div class="row panel-body">
	<form action="{% url 'samples:edit_dispatch' dispatch.pk %}" method="post" role="form">
		{% csrf_token %}
		<table  class="table table-condensed table-bordered">
			<tr>
				<td width="20%">Reference Number:</td>
				<td>{{ dispatch.ref_number }}</td>
			</tr>

			<tr>
				<td>Serial Numbers:</td>
				<td>{{ first }} - {{ last }}</td>
			</tr>
			<tr>				
				<td>Dispatch date:</td>
				<td>{{ dispatch.dispatched_at }}</td>
			</tr>
			<tr>				
				<td>Facility:</td>
				<td>{{ facility_select | safe}}	</td>
			</tr>
			<tr>				
				<td>District:</td>
				<td id="id_district"></td>
			</tr>
			<tr>				
				<td>Hub:</td>
				<td id="id_hub"></td>
			</tr>
			
		</table>
		
		<br>
		<input type="submit" value="Save" class="btn btn-danger">
	</form>
</div>
</div>
	

<script type="text/javascript">
	var date_now = new Date();

	$( function() {
		$("#id_facility").val({{ dispatch.facility_id }});
		set_district_hub(); 
		$("#id_facility").select2({	
    		placeholder: "Select facility", 
    		allowClear: true,
    		width: "30%",
    		tags: "true",	
    	});



    	$(".date").combodate({
    		format: "YYYY-MM-DD HH:mm:ss",
    		template: "D / MMM / YYYY   H : m : s",

    		minYear: 1900,
    		maxYear: date_now.getFullYear(),
    		value: date_now,
    	});

    	$(".day").each(function( index ) {
    		$(this).find(":selected").prependTo($(this));
    	});

    	$("#id_facility").change(function(){
    		set_district_hub();    		    		
    	});

    	$("#id_start").change(function(){
    		ok =  isNumber($(this).val());
    		if(ok==false){
    			alert('expecting a number for start from');
    		}
    	});
  	});


	function set_district_hub(){
		var facility_id = $('#id_facility').val();
		if(facility_id!=''){
			var url =  "/samples/get_district_hub/"+facility_id+"/";
			$.get(url, function(data, status){
				var json_data = JSON.parse(data);
				$("#id_district").html(json_data.district);
				$("#id_hub").html(json_data.hub);
			});	
		}
					
	}

	function isNumber(n) {
		return !isNaN(parseFloat(n)) && isFinite(n);
	}

//422551
</script>


<style type="text/css">
    .x{
    	color: rgb(210, 190, 220);
    	cursor: pointer;
    	font-size: 18px;
    }

    .form-group.required label:before, .form-inline.required label:before {
	  content:"*";
	  color:red;
	}

	.day{
		width:10px;
	}

	.form-group, .form-inline{
		margin-bottom: 4px;
	}

	.form-group > label,.form-inline > label{
		font-size: 14px;
	}
</style>
{% endblock %}

samples/templates/samples/forms.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}


{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/datatables/media/css/dataTables.jqueryui.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/datatables/media/js/jquery.dataTables.js" %}'></script>
{% endblock %}

{% block content %}	

<span class="page-title">Forms</span>

<div class="panel panel-default">
	{%if request.GET.ref_number %}
	<span id="completed" class="alert alert-success vl-alert" role="alert">
		Successfully saved, ref number: {{request.GET.ref_number}}
	</span><br><br>
	{% endif %}
	<i>click on reference number to edit</i>
	<table class='table table-bordered table-striped table table-condensed' id='tab_id'>
		<thead>
			<tr>
				<th>#</th>
				<th>Form</th>
				<th>Reference Number</th>
				<th>Dispatch date</th>	
				<th>Facility</th>
			</tr>
		</thead>
		<tbody>
			{% for f in forms %}
			<tr>
				<td>{{ forloop.counter }}</td>				
				<td>{{ f.form_number }}</td>
				<td><a href="{% url 'samples:edit_dispatch' f.dispatch.pk %}">{{ f.dispatch.ref_number}}</a></td>	
				<td>{{ f.dispatch.dispatched_at | date:"Y-m-d H:m:s"}}</td>	
				<td>{{ f.dispatch.facility }}</td>
			</tr>
			{% endfor %}
		</tbody>
		
	</table>
</div>

<script type="text/javascript">
$(document).ready(function() {
	var oTable = $('#tab_id').dataTable({
		"processing": true,
		"paging":false,
		"order": [[ 3, "asc" ]],
	});
});
</script>
{% endblock %}

samples/templates/samples/generate_forms.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/select2/dist/css/select2.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/select2/dist/js/select2.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/moment/min/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/combodate/src/combodate.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/angular/angular.min.js" %}'></script>
{% endblock %}


{% block content %}	

<div class="page-title">generate request forms</div>
<div class="panel panel-default">
<div class="row panel-body">
	<form action="{% url 'samples:generate_forms' %}" method="post" role="form">
		{% csrf_token %}
		<table  class="table table-condensed table-bordered">
			<tr>
				<td width="20%">Start from (Serial Number):</td>
				<td><input type="number" id="id_start" name="start" required></td>
			</tr>
			<tr>				
				<td>Number of Forms:</td>
				<td>{% select "length" "{50:'50'}" "" "{'class':''}"%}</td>
			</tr>
			<tr>				
				<td>Dispatch date:</td>
				<td>
					<input type="input" id="id_dispatched_at" name="dispatched_at" class="date" required>
				</td>
			</tr>
			<tr>				
				<td>Facility:</td>
				<td>{{ facility_select | safe}}	</td>
			</tr>
			<tr>				
				<td>District:</td>
				<td id="id_district"></td>
			</tr>
			<tr>				
				<td>Hub:</td>
				<td id="id_hub"></td>
			</tr>
			
		</table>
		
		<br>
		<input type="submit" value="Save" class="btn btn-danger">
	</form>
</div>
</div>
	

<script type="text/javascript">
	var date_now = new Date();

	$( function() {

		$("#id_facility").select2({	
    		placeholder: "Select facility", 
    		allowClear: true,
    		width: "30%",
    		tags: "true",
    	});

    	$(".date").combodate({
    		format: "YYYY-MM-DD HH:mm:ss",
    		template: "D / MMM / YYYY   H : m : s",

    		minYear: 1900,
    		maxYear: date_now.getFullYear(),
    		value: date_now,
    	});

    	$(".day").each(function( index ) {
    		$(this).find(":selected").prependTo($(this));
    	});

    	$("#id_facility").change(function(){
    		set_district_hub();    		    		
    	});

    	$("#id_start").change(function(){
    		ok =  isNumber($(this).val());
    		if(ok==false){
    			alert('expecting a number for start from');
    		}
    	});
  	});


	function set_district_hub(){
		var facility_id = $('#id_facility').val();
		if(facility_id!=''){
			var url =  "/samples/get_district_hub/"+facility_id+"/";
			$.get(url, function(data, status){
				var json_data = JSON.parse(data);
				$("#id_district").html(json_data.district);
				$("#id_hub").html(json_data.hub);
			});	
		}
					
	}

	function isNumber(n) {
		return !isNaN(parseFloat(n)) && isFinite(n);
	}

//422551
</script>


<style type="text/css">
    .x{
    	color: rgb(210, 190, 220);
    	cursor: pointer;
    	font-size: 18px;
    }

    .form-group.required label:before, .form-inline.required label:before {
	  content:"*";
	  color:red;
	}

	.day{
		width:10px;
	}

	.form-group, .form-inline{
		margin-bottom: 4px;
	}

	.form-group > label,.form-inline > label{
		font-size: 14px;
	}
</style>
{% endblock %}