api/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'api'
urlpatterns  = [
	url(r'^results/$', views.results, name='results'),
	url(r'^facilities/$', views.facilities, name='facilities'),
	url(r'^samples/$', views.samples, name='samples'),
	url(r'^update_dispatch_details/$', views.update_dispatch_details, name='update_dispatch_details'),
]

results/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from easy_pdf.views import PDFTemplateView
from .views import HelloPDFView
from . import views

app_name = 'results'
urlpatterns  = [
	url(r'^upload/(?P<worksheet_id>[0-9]+)/$', login_required(views.upload), name='upload'),
	url(r'^release_list/(?P<machine_type>[A|R|C])/$', login_required(views.release_list), name='release_list'),
	url(r'^release_results/(?P<worksheet_id>[0-9]+)/$', login_required(views.release_results), name='release_results'),
	url(r'^cobas_upload/$', login_required(views.cobas_upload), name='cobas_upload'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^worksheet/(?P<worksheet_id>[0-9]+)/$', login_required(views.worksheet_results), name='worksheet'),
	url(r'^api', login_required(views.api), name='api'),
	url(r'^anomalies/(?P<worksheet_id>[0-9]+)/$', login_required(views.get_anomalies), name='anomalies'),
	url(r'^intervene_list/$', login_required(views.intervene_list), name='intervene_list'),
	url(r'^reschedule/(?P<result_pk>[0-9]+)/$', login_required(views.reschedule), name='reschedule'),
	url(r'^authorize_sample/$', login_required(views.authorize_sample), name='authorize_sample'),
	url(r'^release_sample/$', login_required(views.release_sample), name='release_sample'),
	url(r'^print_results/(?P<result_id>[0-9]+)/(?P<worksheet_id>[0-9]+)/$', login_required(views.print_results), name='print_results'),
	#url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^hello.pdf$', HelloPDFView.as_view()),
]

viral_load2/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from home import views as home_views, session

urlpatterns = [
	url(r'^$', home_views.home, name='home_page'),
	url(r'^login/', home_views.login_page, name='login_page'),
	url(r'^login_attempt/', home_views.login_attempt, name='login_attempt'),
	url(r'^logout/', home_views.logout, name='logout'),
	url(r'^quick_stats/', home_views.quick_stats, name='quick_stats'),
	url(r'^change-password/$', auth_views.password_change, {'post_change_redirect': 'home_page'}, name='password_change'),
	url(r'^admin/', admin.site.urls),
	url(r'^samples/', include('samples.urls')),
	url(r'^worksheets/', include('worksheets.urls')),
	url(r'^results/', include('results.urls')),
	url(r'^api/', include('api.urls')),
]

worksheets/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'worksheets'
urlpatterns  = [
	url(r'^create/(?P<machine_type>[A|R|C])$', login_required(views.create), name='create'),
	url(r'^attach_samples/(?P<worksheet_id>[0-9]+)/$', login_required(views.attach_samples), name='attach_samples'),
	url(r'^show/(?P<worksheet_id>[0-9]+)/$', login_required(views.show), name='show'),
	url(r'^edit/(?P<worksheet_id>[0-9]+)/$', login_required(views.edit), name='edit'),
	url(r'^vlprint/(?P<worksheet_id>[0-9]+)/$', login_required(views.vlprint), name='vlprint'),
	url(r'^list/$', login_required(views.list), name='list'),
	url(r'^pdf/(?P<worksheet_id>[0-9]+)/$', login_required(views.generate_pdf), name='pdf'),
	url(r'^list_json/$', login_required(views.ListJson.as_view()), name='list_json'),
	url(r'^authorize_list/(?P<machine_type>[A|R|C])/$', login_required(views.authorize_list), name='authorize_list'),
	url(r'^authorize_results/(?P<worksheet_id>[0-9]+)/$', login_required(views.authorize_results), name='authorize_results'),
	url(r'^pending_samples/$', login_required(views.pending_samples), name='get_pending_samples'),
	url(r'^pending_envelopes/$', login_required(views.pending_envelopes), name='pending_envelopes'),
	url(r'^delete/(?P<pk>[0-9]+)/$', login_required(views.delete), name='delete'),
	url(r'^reg_info/(?P<machine_type>[A|R|C])/$', login_required(views.reg_info), name='reg_info'),
	url(r'^get_instrument_id/$', login_required(views.get_instrument_id), name='get_instrument_id'),
	url(r'^barcodes/(?P<pk>[0-9]+)/$', login_required(views.barcodes), name='barcodes'),
	#url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

results/models.py
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

import samples.models as samples
import backend.models as backend
import worksheets.models as worksheets

# Create your models here.

#track 
class Result(models.Model):
	METHOD_CHOICES = ( ('A', 'Abbott Real time HIV-1 PCR'), ('R', 'HIV-1 RNA PCR Roche'), ('C', 'HIV-1 RNA PCR Roche'))
	sample = models.OneToOneField(samples.Sample, on_delete=models.CASCADE)
	repeat_test = models.PositiveSmallIntegerField(default=2,choices=( (1, 'YES'),(2, 'NO'), (3, 'PROPOSED') ))
	result1 = models.TextField()
	result2 = models.TextField()
	result3 = models.TextField()
	result4 = models.TextField()
	result5 = models.TextField()

	suppressed = models.PositiveSmallIntegerField(default=3,choices=( (1, 'YES'),(2, 'NO'), (3, 'UNKNOWN') ))
	result_numeric = models.IntegerField(null=True)
	printed = models.IntegerField(null=True)
	result_alphanumeric = models.TextField()
	method = models.CharField(max_length=1, null=True, choices=METHOD_CHOICES)
	result_upload_date = models.DateTimeField(null=True)
	test_date = models.DateTimeField(null=True)

	test_by = models.ForeignKey(User,null=True, related_name='test_by')

	authorised = models.BooleanField(default=False)
	authorised_by = models.ForeignKey(User, related_name='authorised_by', null=True)
	authorised_at = models.DateTimeField(null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.sample.form_number

	class Meta:
		db_table = 'vl_results'
	

#track sample sample printing and dispatch
class ResultsQC(models.Model):
	result = models.OneToOneField(Result, on_delete=models.CASCADE)
	released = models.BooleanField(default=False)
	released_by = models.ForeignKey(User, related_name='released_by', null=True)
	released_at = models.DateTimeField(null=True)
	comments = models.TextField(null=True)

	class Meta:
		db_table = 'vl_results_qc'

class ResultsDispatch(models.Model):
	sample = models.OneToOneField(samples.Sample, on_delete=models.CASCADE)
	dispatch_type = models.CharField(max_length=1, null=True, choices=( ('P', 'Printed'),('D', 'Downloaded') ))
	dispatch_date = models.DateTimeField(null=True)
	dispatched_by = models.CharField(max_length=128, null=True)

	class Meta:
		db_table = 'vl_results_dispatch'

#track worksheets whose results have been uploaded
class WorksheetResultsUpload(models.Model):
	worksheet = models.ForeignKey(worksheets.Worksheet)
	results_file = models.FileField(upload_to='results')
	multiplier = models.IntegerField(default=1)
	upload_date = models.DateTimeField(auto_now_add=True)
	uploaded_by = models.ForeignKey(User, related_name='uploaded_by')

	def clean(self):
		file_name = self.results_file.name		
		if self.worksheet == 'R' and file_name.endswith('.csv') is not True:
			raise ValidationError(_("Expecting a csv file"))
		if self.worksheet == 'A' and file_name.endswith('.txt') is not True:
			raise ValidationError(_("Expecting a txt file"))

	class Meta:
		db_table = 'vl_worksheet_results_uploads'	

class CobasResultsUpload(models.Model):
	reference_number = models.CharField(max_length=128, null=True)
	results_file = models.FileField(upload_to='results')
	multiplier = models.IntegerField(default=1)
	upload_date = models.DateTimeField(auto_now_add=True)
	cobas_uploaded_by = models.ForeignKey(User, related_name='cobas_uploaded_by')

	def clean(self):
		file_name = self.results_file.name		
		if file_name.endswith('.csv') is not True:
			raise ValidationError(_("Expecting a csv file"))

	class Meta:
		db_table = 'vl_cobas_results_uploads'	

worksheets/models.py
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from samples.models import Sample

import backend.models as backend

#'awaiting_results','has_results','passed_lab_qc','passed_data_qc'

# Create your models here.
MACHINE_TYPES = ( ('A', 'Abbott'), ('R', 'Roche CAP/CTM'), ('C', 'Cobas 8800') )
STAGE_CHOICES = ( (1, 'awaiting_results'),(2, 'has_results'), (3, 'passed_lab_qc'), (4, 'passed_data_qc') )

class Worksheet(models.Model):
	
	samples = models.ManyToManyField(Sample, through='WorksheetSample')
	worksheet_reference_number = models.CharField(max_length=128)
	machine_type = models.CharField(max_length=1, choices=MACHINE_TYPES)
	sample_type = models.CharField(max_length=1, choices=Sample.SAMPLE_TYPES)
	sample_prep = models.CharField(max_length=64,null=True, blank=True)
	sample_prep_expiry_date = models.DateField(null=True, blank=True)
	bulk_lysis_buffer = models.CharField(max_length=64, null=True, blank=True)
	bulk_lysis_buffer_expiry_date = models.DateField(null=True, blank=True)
	control = models.CharField(max_length=64, null=True, blank=True)
	control_expiry_date = models.DateField(null=True, blank=True)
	calibrator = models.CharField(max_length=64, null=True, blank=True)
	calibrator_expiry_date = models.DateField(null=True, blank=True)
	include_calibrators = models.BooleanField(default=False)
	amplication_kit = models.CharField(max_length=64, null=True, blank=True)
	amplication_kit_expiry_date = models.DateField(null=True, blank=True)
	assay_date = models.DateTimeField()
	generated_by = models.ForeignKey(User, related_name='generated_by')
	worksheet_updated_by = models.ForeignKey(User, related_name='worksheet_updated_by', null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	stage = models.PositiveSmallIntegerField(choices=STAGE_CHOICES, default=1)
	worksheet_medical_lab = models.ForeignKey(backend.MedicalLab, related_name='worksheet_medical_lab', default=1)

	class Meta:
		db_table = 'vl_worksheets'


#Attaching samples to work sheet
class WorksheetSample(models.Model):
	worksheet = models.ForeignKey(Worksheet, on_delete=models.CASCADE)
	sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
	stage = models.PositiveSmallIntegerField(choices=STAGE_CHOICES, default=1)
	sample_run = models.PositiveSmallIntegerField(default=1)
	instrument_id = models.CharField(max_length=64, null=True, blank=True)
	rack_id = models.CharField(max_length=64, null=True, blank=True)

	class Meta:
		db_table = 'vl_worksheet_samples'


class WorksheetPrinting(models.Model):
	worksheet = models.OneToOneField(Worksheet, on_delete=models.CASCADE)
	worksheet_printed_by = models.ForeignKey(User, related_name='worksheet_printed_by')
	printed_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'vl_worksheet_printing'

results/forms.py
from django import forms

from .models import WorksheetResultsUpload,CobasResultsUpload
from home import utils

class UploadForm(forms.ModelForm):
	
	class Meta:
		model = WorksheetResultsUpload
		fields = ('worksheet', 'multiplier', 'results_file',)
		widgets = {
			'worksheet': forms.HiddenInput(),
			'multiplier': forms.TextInput(attrs=utils.ATTRS2),
			'results_file': forms.FileInput(attrs={"class": "form-control-file"}),
		}

class CobasUploadForm(forms.ModelForm):
	
	class Meta:
		model = CobasResultsUpload
		fields = ('reference_number', 'multiplier', 'results_file',)
		widgets = {
			'reference_number': forms.TextInput(attrs=utils.ATTRS),
			'multiplier': forms.TextInput(attrs=utils.ATTRS2),
			'results_file': forms.FileInput(attrs={"class": "form-control-file"}),
		}

results/templates/results/cobas_upload.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/moment/min/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/combodate/src/combodate.js" %}'></script>
{% endblock %}

{% block content %}	
	<span class="page-title">Upload results</span>		
	<div class="panel panel-default">
		<div class="panel-body">
			
			<form action="{% url 'results:cobas_upload' %}" method="post" role="form" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="form-group">
					{{ form.reference_number.label_tag}}
					{{ form.reference_number.errors}}
					{{ form.reference_number }}
				</div>
				<div class="form-group">
					{{ form.results_file.label_tag}}
					{{ form.results_file.errors}}
					{{ form.results_file }}
				</div>

				<div class="form-group">
					{{ form.multiplier.label_tag}}
					{{ form.multiplier.errors}}
					{{ form.multiplier }}
				</div>

				<div class="form-group">
					<label for="id_date_format">Date Format:</label>
					<select class="form-control input-sm w-sm" name="date_format">
						<option value="1">DD-MMM-YYYY Time (12HRS)</option>	
						<option value="2">MM/DD/YYYY Time (24HRS)</option>						
					</select>
				</div>
				{{ form.worksheet }}
				<input type="submit" value="Upload" class="btn btn-danger btn-submit ">
				
			</form>
		</div>
	</div>
	<script type="text/javascript">
	/*var date_now = new Date();
	var yr_now = date_now.getFullYear();
	$( function() {
		$(".date").combodate({
    		format: "YYYY-MM-DD",
    		template: "D MMM YYYY",
    		customClass: "form-control input-sm",
    		maxYear: yr_now+30,
    		minYear: yr_now-1,
    		yearDescending: false,    		
    	});
	})*/

	</script>
{% endblock %}

results/templates/results/release_list.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/datatables/media/css/dataTables.jqueryui.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/datatables/media/js/jquery.dataTables.js" %}'></script>
{% endblock %}

{% block content %}	

<div class="page-title">Worksheets :: {{ machine_type }}</div>

<div class="panel panel-default">
	<ul id="tabs_a" class="nav nav-tabs">
	    <li {% if request.GET.tab != 'released' %}class='active'{% endif %}>
	    	<a href="?tab=pending">Pending</a>
	    </li>
	    <li {% if request.GET.tab == 'released' %}class='active'{% endif %}>
	    	<a href="?tab=released">Released</a>
	    </li>
	</ul>
	<div class="tab-content">
		<table class='table table-bordered table-striped table table-condensed' id='tab_id'>
			<thead>
				<tr>
					<td>#</td>
					<th>Worksheet Ref Number</th>
					<th>Machine Type</th>
					<th>Sample Type</th>
					<th>Date Created</th>
				</tr>
			</thead>
			<tbody>
				{% for worksheet in worksheets %}
				<tr>
					<td>{{ forloop.counter }}</td>
					<td><a href="{% url 'results:release_results' worksheet.id %}">{{ worksheet.worksheet_reference_number }}</a></td>
					<td>{{ worksheet.get_machine_type_display }}</td>
					<td>{{ worksheet.get_sample_type_display }}</td>
					<td>{{ worksheet.created_at | date:"Y-m-d" }}</td>
				</tr>
				{% endfor %}
				
			</tbody>
		</table>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var oTable = $('#tab_id').dataTable({
		"processing": true,
		"paging":false,
	});
});
</script>

{% endblock %}

results/templates/results/release_results.html
{% extends "home/layout.html" %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href='{% static "home/vendor/datatables/media/css/dataTables.jqueryui.min.css" %}'>
{% endblock %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/jquery-barcode/jquery-barcode.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/datatables/media/js/jquery.dataTables.js" %}'></script>
{% endblock %}

{% block content %}	
	<span class="page-title">WORKSHEET</span>		
	<div class="panel panel-default" style="overflow-y:auto">
		<div class="panel-body">
			<form action="/results/release_results/{{ worksheet.pk }}/" method="post" role="form">	
			{% csrf_token %}	
			<div class="worksheet" id="content" >
				<div class="row" >
					<div class="col-md-4">Worksheet Ref Number: <u>{{ worksheet.worksheet_reference_number }}</u></div>
					<div class="col-md-4">Machine Type: <u>{{ worksheet.get_machine_type_display }}</u></div>
					<div class="col-md-4">Sample Type: <u>{{ worksheet.get_sample_type_display }}</u></div>
				</div>
				<br>
				<table class="table table-striped table-condensed table-bordered" id="samples-table" >
					<thead>
						<th>Location&nbsp;ID&nbsp;&nbsp;&nbsp;</th>
		                <th width="1%">Form Number</th>
		                <th>Facility</th>
		                <th>District</th>                
		                <th>Hep Number</th>
		                <th>Other ID</th>
		                <th>Gender</th>
		                <th width="1%">Date&nbsp;of collection&nbsp;&nbsp;&nbsp;</th>
		                <th width="1%">Date&nbsp;received at CHPL</th>
		                <th>Result</th>
		                <th>Choose</th>
		                <th/>
					</thead>
					<tbody>
						{% for s in worksheet.worksheetsample_set.all %}
						{% if s.sample.result.repeat_test == 2 %}						
						<tr>
							<td>{{ s.sample.locator_category }}{{ s.sample.envelope.envelope_number }}/{{ s.sample.locator_position }}</td>
							<td>{{ s.sample.form_number }}</td>
							<td>{{ s.sample.facility.facility }}</td>
							<td>{{ s.sample.facility.district.district }} </td>
							<td>{{ s.sample.patient.hep_number }}</td>
							<td>{{ s.sample.patient.other_id }}</td>
							<td>{{ s.sample.patient.get_gender_display }}</td>
							<td>{{ s.sample.date_collected | date:"Y-m-d" }}</td>
							
							<td>{{ s.sample.date_received | date:"Y-m-d" }}</td>
							<td>{{ s.sample.result.result_alphanumeric }}</td>
							
							<td>
								{% if s.sample.result.resultsqc.released == 1 %}
									Released
								{% elif s.sample.result.resultsqc.released == 0 %}
									Retained
								{% else %}
									<label><input type='radio' required='true' name='choices{{ s.sample.result.pk }}' class='choices r' result-pk="{{ s.sample.result.pk }}" value='release'> Release</label>
									<label><input type='radio' required='true' name='choices{{ s.sample.result.pk }}' class='choices' result-pk="{{ s.sample.result.pk }}" value='retain'> Retain</label>
									<div class="comments" id="comments_sect{{ s.sample.result.pk }}" >
									<input type="text"  name='comments{{ s.sample.result.pk }}' placeholder="comments" id="comment{{ s.sample.result.pk }}" class="comments_input" result-pk="{{ s.sample.result.pk }}" value="">
									<!-- <span class="btn btn-primary btn-xs comments_save" result-pk="{{ s.sample.result.pk }}">save</span> -->
									</div>
								{% endif %}
							</td>
							<td><span id="saved{{ s.sample.result.pk }}" class="status alert alert-success vl-alert" role="alert">saved&nbsp;</span></td>
						</tr>
						{% endif %}
						
						{% endfor %}
					</tbody>
				</table>
				<input type="hidden" name="push_worksheet" value='1'>
				<input type='submit' value='Save and push to next stage' class='btn btn-sm btn-danger'><br><br><br>
			</div>
			</form>
		</div>
	</div>
	<script type="text/javascript">
	var num_pending_release = $('.r').length;
	var num_released_currently = 0;
	 $(function() {
	 	var oTable = $('#samples-table').dataTable({
			"processing": true,
			"paging":false,
			"order": [[ 0, "asc" ]],
		});
        $(".status").hide();
        $(".comments").hide();
      });

	 $(".choices").on("click",function(){
	 	var choice = $(this).val();
	 	var result_pk = $(this).attr('result-pk');
	 	if(choice == 'release'){
	 		var params = {csrfmiddlewaretoken:"{{ csrf_token }}", result_pk: result_pk, choice: choice};
	 		saveDetails(params);
	 		$('#comments_sect'+result_pk).hide();
	 	}else{
	 		$('#comments_sect'+result_pk).show();
	 	} 	

	 });

	 $(".comments_input").on("change", function(){
	 	var result_pk = $(this).attr('result-pk');
	 	var comments = $("#comment"+result_pk).val();
	 	var params = {csrfmiddlewaretoken:"{{ csrf_token }}", result_pk: result_pk, choice: 'retain', comments:comments};
	 	saveDetails(params);
	 });

	 saveDetails = function(params){
	 	num_released_currently = num_released_currently+1;
	 	if(num_released_currently == num_pending_release){
	 		params.completed = 'yes';
	 	}
	 	$.post("/results/release_results/{{ worksheet.pk }}/", params).done(function( data ) {
		    $("#saved"+params.result_pk).show();
		  });
	 }
	 $(".x").on("click", function(){
	 	$(this).parent().hide();
	 });
	</script>

{% endblock %}

results/templates/results/upload.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}

{% block js %}
	<script type="text/javascript" src='{% static "home/vendor/moment/min/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "home/vendor/combodate/src/combodate.js" %}'></script>
{% endblock %}

{% block content %}	
	<span class="page-title">Upload results</span>		
	<div class="panel panel-default">
		<div class="panel-body">
			
			<form action="{% url 'results:upload' worksheet.pk %}" method="post" role="form" enctype="multipart/form-data" id="form">
				{% csrf_token %}
				<div class="form-inline">
					<label>Ref number: </label> <u>{{ worksheet.worksheet_reference_number }}</u>
				</div>

				<div class="form-inline">
					<label>Machine type: </label> <u>{{ worksheet.get_machine_type_display }}</u>
				</div>

				<div class="form-inline">
					<label>Sample type: </label> <u>{{ worksheet.get_sample_type_display }}</u>
				</div>

				<div class="form-group">
					{{ form.results_file.label_tag}}
					{{ form.results_file.errors}}
					{{ form.results_file }}
				</div>

				<div class="form-group">
					{{ form.multiplier.label_tag}}
					{{ form.multiplier.errors}}
					{{ form.multiplier }}
				</div>

				{% if worksheet.machine_type == 'R' %}
				<div class="form-group">
					<label for="id_date_format">Date Format:</label>
					<select class="form-control input-sm w-sm" name="date_format">
						<option value="1">YYYY/MM/DD Time</option>	
						<option value="2">MM/DD/YYYY Time</option>
						<option value="3">DD/MM/YYYY Time</option>					
					</select>
				</div>
				{% endif %}

				{{ form.worksheet }}
				<div id="id_anomalies"></div>
				<input id="id_upload" type="submit" value="Upload" class="btn btn-danger btn-submit ">
				
			</form>
		</div>
	</div>
	<script type="text/javascript">
	$(function(){ $('#id_upload').hide(); })
	$("#id_results_file").on("change", function(){
		var form = $('form')[0];
		var formData = new FormData(form);
		formData.append('results_file', this.files[0]);
		formData.append('csrfmiddlewaretoken', $("[name=csrfmiddlewaretoken]").val());
		$.ajax({
		   url : '/results/anomalies/{{ worksheet.pk }}/',
		   type : 'POST',
		   data : formData,
		   processData: false,  // tell jQuery not to process the data
		   contentType: false,  // tell jQuery not to set contentType
		   success : function(data) {
		       if(data==0){
		       	$('#id_upload').show();
		       	$("#id_anomalies").hide();
		       }else{		       	 
		       	$("#id_upload").hide();
		       	var $el = $('#id_results_file');
		       	$el.wrap('<form>').closest('form').get(0).reset();
		       	$el.unwrap();	
		       	$("#id_anomalies").html(data);       
		       	//alert('the worksheet has duplicate samples');
		       }
		   }
		});
	});
	/*var date_now = new Date();
	var yr_now = date_now.getFullYear();
	$( function() {
		$(".date").combodate({
    		format: "YYYY-MM-DD",
    		template: "D MMM YYYY",
    		customClass: "form-control input-sm",
    		maxYear: yr_now+30,
    		minYear: yr_now-1,
    		yearDescending: false,    		
    	});
	})*/

	</script>
{% endblock %}

results/templates/results/worksheet_results.html
{% extends "home/layout.html" %}
{% load form_tags %}
{% load staticfiles %}


{% block content %}	
	<span class="page-title">Worksheet Results</span>		
	<div class="panel panel-default">
		<div class="panel-body">

			{% for sample in worksheet.samples.all %}
			{% include "results/_sample_result.html" %}
			{% endfor %}			
		</div>
	</div>
	<script type="text/javascript">
	/*var date_now = new Date();
	var yr_now = date_now.getFullYear();
	$( function() {
		$(".date").combodate({
    		format: "YYYY-MM-DD",
    		template: "D MMM YYYY",
    		customClass: "form-control input-sm",
    		maxYear: yr_now+30,
    		minYear: yr_now-1,
    		yearDescending: false,    		
    	});
	})*/

	</script>
{% endblock %}